version: '3.9'
services:
  bot:
    image: bot_image:latest
    container_name: bot_image
    volumes:
      - ${PG_DATA_MASTER_DIR}/data/log:/code/pg_log
  db-master:
    image: bitnami/postgresql
    container_name: db_image
    restart: always
    shm_size: 128mb
    volumes:
        - 'postgresql_master_data:/bitnami/postgresql'
        - 'postgresql_master_conf:/opt/bitnami/postgresql/conf'
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_DATA_DIR: ${POSTGRESQL_DATA_DIR}
      POSTGRESQL_PGAUDIT_LOG: READ,WRITE
      POSTGRESQL_LOG_HOSTNAME: true
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: ${POSTGRESQL_REPLICATION_USER}
      POSTGRESQL_REPLICATION_PASSWORD: ${POSTGRESQL_REPLICATION_PASSWORD}
      POSTGRESQL_USERNAME: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_MASTER}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
      ALLOW_EMPTY_PASSWORD: yes

  db-slave:
    image: bitnami/postgresql
    container_name: db_repl_image
    restart: always
    shm_size: 128mb
    volumes:
        - 'postgresql_slave_data:/bitnami/postgresql'
        - 'postgresql_slave_conf:/opt/bitnami/postgresql/conf'
    ports:
      - 5433:5432
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_SLAVE}
      POSTGRESQL_MASTER_HOST: db-master
      POSTGRESQL_PGAUDIT_LOG: READ,WRITE
      POSTGRESQL_LOG_HOSTNAME: true
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_REPLICATION_USER: ${POSTGRESQL_REPLICATION_USER}
      POSTGRESQL_REPLICATION_PASSWORD: ${POSTGRESQL_REPLICATION_PASSWORD}
      POSTGRESQL_MASTER_PORT_NUMBER: 5432
volumes:
  postgresql_master_data:
    driver: local
    driver_opts:
      type: none
      device: ${PG_DATA_MASTER_DIR}
      o: bind
  
  postgresql_slave_data:
   driver: local
   driver_opts:
     type: none
     device: ${PG_DATA_SLAVE_DIR}
     o: bind

  postgresql_master_conf:
    driver: local
    driver_opts:
      type: none
      device: ${PG_CONF_MASTER_DIR}
      o: bind   

  postgresql_slave_conf:
    driver: local
    driver_opts:
      type: none
      device: ${PG_CONF_SLAVE_DIR}
      o: bind       